# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""
Shared migration data for PyRIT version upgrades.

This module is the single source of truth for all known breaking changes
between PyRIT versions. Both the notebook_upgrade_helper (reactive) and
notebook_converter (proactive) consume these definitions.

Rules are split into two categories:

- **Auto-detected** rules (import moves, class renames) can be regenerated
  by running ``python -m pyrit.common.generate_migration_data``, which
  scans the codebase for ``print_deprecation_message`` calls in deprecation
  shims.

- **Manual** rules (kwarg renames, method renames) describe runtime behavior
  changes that cannot be detected from deprecation shims and must be
  maintained by hand.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ImportRename:
    """A renamed or moved import symbol."""

    old_module: str
    old_name: str
    new_module: str
    new_name: str
    removed_in: str | None = None
    source: Literal["shim", "manual"] = "manual"


@dataclass(frozen=True)
class ModuleRename:
    """A renamed or removed module (bare ``import X`` rewrites)."""

    old_module: str
    new_module: str
    removed_in: str | None = None
    source: Literal["shim", "manual"] = "manual"


@dataclass(frozen=True)
class ClassRename:
    """A renamed class (word-boundary-aware substitution in usage sites)."""

    old_name: str
    new_name: str


@dataclass(frozen=True)
class KwargRename:
    """A renamed keyword argument, scoped to a callable context pattern."""

    context_pattern: str | None
    old_kwarg: str
    new_kwarg: str
    confidence: Literal["auto", "suggestion"] = "auto"


@dataclass(frozen=True)
class MethodRename:
    """A renamed method, optionally scoped to a receiver context pattern."""

    context_pattern: str | None
    old_method: str
    new_method: str
    confidence: Literal["auto", "suggestion"] = "auto"


# ---------------------------------------------------------------------------
# Auto-detected rules (regenerated by generate_migration_data.py)
# ---------------------------------------------------------------------------
# ▼▼▼ BEGIN GENERATED IMPORT RENAMES ▼▼▼

IMPORT_RENAMES: list[ImportRename] = [
    # === Orchestrator → Attack (removed in 0.13.0, no deprecation shims) ===
    ImportRename("pyrit.orchestrator", "PromptSendingOrchestrator", "pyrit.executor.attack", "PromptSendingAttack", removed_in="0.13.0", source="manual"),
    ImportRename("pyrit.orchestrator", "RedTeamingOrchestrator", "pyrit.executor.attack", "RedTeamingAttack", removed_in="0.13.0", source="manual"),
    ImportRename("pyrit.orchestrator", "CrescendoOrchestrator", "pyrit.executor.attack", "CrescendoAttack", removed_in="0.13.0", source="manual"),
    ImportRename("pyrit.orchestrator", "PAIROrchestrator", "pyrit.executor.attack", "PAIRAttack", removed_in="0.13.0", source="manual"),
    ImportRename("pyrit.orchestrator", "PairOrchestrator", "pyrit.executor.attack", "PAIRAttack", removed_in="0.13.0", source="manual"),
    ImportRename("pyrit.orchestrator", "TreeOfAttacksWithPruningOrchestrator", "pyrit.executor.attack", "TreeOfAttacksWithPruningAttack", removed_in="0.13.0", source="manual"),
    ImportRename("pyrit.orchestrator", "MultiTurnOrchestrator", "pyrit.executor.attack", "MultiTurnAttackStrategy", removed_in="0.13.0", source="manual"),
    ImportRename("pyrit.orchestrator", "FlipAttackOrchestrator", "pyrit.executor.attack", "FlipAttack", removed_in="0.13.0", source="manual"),
    ImportRename("pyrit.orchestrator", "SkeletonKeyOrchestrator", "pyrit.executor.attack", "SkeletonKeyAttack", removed_in="0.13.0", source="manual"),
    ImportRename("pyrit.orchestrator", "ScoringOrchestrator", "pyrit.executor.attack", "AttackExecutor", removed_in="0.13.0", source="manual"),
    # === Scorer printer moves (shim-detected, removed in 0.16.0) ===
    ImportRename("pyrit.score.printer", "ConsoleScorerPrinter", "pyrit.output.scorer.pretty", "PrettyScorerMemoryPrinter", removed_in="0.16.0", source="shim"),
    ImportRename("pyrit.score.printer", "ScorerPrinter", "pyrit.output.scorer.base", "ScorerPrinterBase", removed_in="0.16.0", source="shim"),
    # === Attack result printer moves (shim-detected, removed in 0.16.0) ===
    ImportRename("pyrit.executor.attack.printer", "ConsoleAttackResultPrinter", "pyrit.output.attack_result.pretty", "PrettyAttackResultMemoryPrinter", removed_in="0.16.0", source="shim"),
    ImportRename("pyrit.executor.attack.printer", "AttackResultPrinter", "pyrit.output.attack_result.base", "AttackResultPrinterBase", removed_in="0.16.0", source="shim"),
    ImportRename("pyrit.executor.attack.printer", "MarkdownAttackResultPrinter", "pyrit.output.attack_result.markdown", "MarkdownAttackResultMemoryPrinter", removed_in="0.16.0", source="shim"),
    # === Scenario printer moves (shim-detected, removed in 0.16.0) ===
    ImportRename("pyrit.scenario.printer", "ConsoleScenarioResultPrinter", "pyrit.output.scenario_result.pretty", "PrettyScenarioResultMemoryPrinter", removed_in="0.16.0", source="shim"),
    ImportRename("pyrit.scenario.printer", "ScenarioResultPrinter", "pyrit.output.scenario_result.base", "ScenarioResultPrinterBase", removed_in="0.16.0", source="shim"),
    # === Deep sub-module shims (same moves, deeper import paths) ===
    ImportRename("pyrit.score.printer.console_scorer_printer", "ConsoleScorerPrinter", "pyrit.output.scorer.pretty", "PrettyScorerMemoryPrinter", removed_in="0.16.0", source="shim"),
    ImportRename("pyrit.executor.attack.printer.console_printer", "ConsoleAttackResultPrinter", "pyrit.output.attack_result.pretty", "PrettyAttackResultMemoryPrinter", removed_in="0.16.0", source="shim"),
    ImportRename("pyrit.executor.attack.printer.markdown_printer", "MarkdownAttackResultPrinter", "pyrit.output.attack_result.markdown", "MarkdownAttackResultMemoryPrinter", removed_in="0.16.0", source="shim"),
    ImportRename("pyrit.scenario.printer.console_printer", "ConsoleScenarioResultPrinter", "pyrit.output.scenario_result.pretty", "PrettyScenarioResultMemoryPrinter", removed_in="0.16.0", source="shim"),
    # === Identifier moves (shim-detected, removed in 0.16.0) ===
    ImportRename("pyrit.models", "ScorerIdentifier", "pyrit.models", "ComponentIdentifier", removed_in="0.16.0", source="shim"),
    # === Storage I/O moves (shim-detected, removed in 0.17.0) ===
    ImportRename("pyrit.models.storage_io", "StorageIO", "pyrit.memory.storage.storage", "StorageIO", removed_in="0.17.0", source="shim"),
    ImportRename("pyrit.models.storage_io", "AzureBlobStorageIO", "pyrit.memory.storage.storage", "AzureBlobStorageIO", removed_in="0.17.0", source="shim"),
    ImportRename("pyrit.models.storage_io", "DiskStorageIO", "pyrit.memory.storage.storage", "DiskStorageIO", removed_in="0.17.0", source="shim"),
    ImportRename("pyrit.models.storage_io", "SupportedContentType", "pyrit.memory.storage.storage", "SupportedContentType", removed_in="0.17.0", source="shim"),
    # === Serializer moves (shim-detected, removed in 0.17.0) ===
    ImportRename("pyrit.models.data_type_serializer", "DataTypeSerializer", "pyrit.memory.storage.serializers", "DataTypeSerializer", removed_in="0.17.0", source="shim"),
    ImportRename("pyrit.models.data_type_serializer", "data_serializer_factory", "pyrit.memory.storage.serializers", "data_serializer_factory", removed_in="0.17.0", source="shim"),
    ImportRename("pyrit.models.data_type_serializer", "TextDataTypeSerializer", "pyrit.memory.storage.serializers", "TextDataTypeSerializer", removed_in="0.17.0", source="shim"),
    ImportRename("pyrit.models.data_type_serializer", "ImagePathDataTypeSerializer", "pyrit.memory.storage.serializers", "ImagePathDataTypeSerializer", removed_in="0.17.0", source="shim"),
    ImportRename("pyrit.models.data_type_serializer", "AudioPathDataTypeSerializer", "pyrit.memory.storage.serializers", "AudioPathDataTypeSerializer", removed_in="0.17.0", source="shim"),
    ImportRename("pyrit.models.data_type_serializer", "ErrorDataTypeSerializer", "pyrit.memory.storage.serializers", "ErrorDataTypeSerializer", removed_in="0.17.0", source="shim"),
    ImportRename("pyrit.models.data_type_serializer", "URLDataTypeSerializer", "pyrit.memory.storage.serializers", "URLDataTypeSerializer", removed_in="0.17.0", source="shim"),
    # === Initializer rename (shim-detected, removed in 0.16.0) ===
    ImportRename("pyrit.setup.initializers", "InitializerParameter", "pyrit.setup.initializers", "Parameter", removed_in="0.16.0", source="shim"),

    # =================================================================
    # Pre-0.10.0 breaking changes (historical, no deprecation shims)
    # =================================================================

    # --- v0.10.0: Core data model renames ---
    ImportRename("pyrit.models", "PromptRequestResponse", "pyrit.models", "Message", removed_in="0.10.0", source="manual"),
    ImportRename("pyrit.models", "PromptRequestPiece", "pyrit.models", "MessagePiece", removed_in="0.10.0", source="manual"),

    # --- v0.10.0: Additional orchestrator → executor moves ---
    ImportRename("pyrit.orchestrator", "ContextComplianceOrchestrator", "pyrit.executor.attack", "ContextComplianceAttack", removed_in="0.10.0", source="manual"),
    ImportRename("pyrit.orchestrator", "ManyShotJailbreakOrchestrator", "pyrit.executor.attack", "ManyShotJailbreakAttack", removed_in="0.10.0", source="manual"),
    ImportRename("pyrit.orchestrator", "ViolentDurianOrchestrator", "pyrit.executor.attack", "ViolentDurianAttack", removed_in="0.10.0", source="manual"),
    ImportRename("pyrit.orchestrator", "RolePlayOrchestrator", "pyrit.executor.attack", "RolePlayAttack", removed_in="0.10.0", source="manual"),
    ImportRename("pyrit.orchestrator", "XPIAOrchestrator", "pyrit.executor.workflow", "XPIAWorkflow", removed_in="0.10.0", source="manual"),
    ImportRename("pyrit.orchestrator", "XPIATestOrchestrator", "pyrit.executor.workflow", "XPIATestWorkflow", removed_in="0.10.0", source="manual"),
    ImportRename("pyrit.orchestrator", "XPIAManualProcessingOrchestrator", "pyrit.executor.workflow", "XPIAManualProcessingWorkflow", removed_in="0.10.0", source="manual"),
    ImportRename("pyrit.orchestrator", "FuzzerOrchestrator", "pyrit.executor.promptgen", "FuzzerGenerator", removed_in="0.10.0", source="manual"),
    ImportRename("pyrit.orchestrator", "QuestionAnsweringBenchmarkOrchestrator", "pyrit.executor.benchmark", "QuestionAnsweringBenchmark", removed_in="0.10.0", source="manual"),

    # --- v0.10.0: Target renames ---
    ImportRename("pyrit.prompt_target", "OpenAIDALLETarget", "pyrit.prompt_target", "OpenAIImageTarget", removed_in="0.10.0", source="manual"),

    # --- v0.10.0: Converter renames ---
    ImportRename("pyrit.prompt_converter", "TextToHexConverter", "pyrit.prompt_converter", "BinAsciiConverter", removed_in="0.10.0", source="manual"),

    # --- v0.10.0: Setup/initialization ---
    ImportRename("pyrit.common", "initialize_pyrit", "pyrit.setup", "initialize_pyrit_async", removed_in="0.10.0", source="manual"),

    # --- v0.9.0: Result class rename ---
    ImportRename("pyrit.orchestrator", "MultiTurnAttackResult", "pyrit.models", "OrchestratorResult", removed_in="0.9.0", source="manual"),

    # --- v0.6.0: SeedPrompts rename ---
    ImportRename("pyrit.models", "NormalizerRequestPieces", "pyrit.models", "SeedPrompts", removed_in="0.6.0", source="manual"),

    # --- v0.5.0: OpenAI target unification ---
    ImportRename("pyrit.prompt_target", "AzureOpenAIChatTarget", "pyrit.prompt_target", "OpenAIChatTarget", removed_in="0.5.0", source="manual"),

    # --- v0.5.0: Converter merge ---
    ImportRename("pyrit.prompt_converter", "HomoglyphGeneratorConverter", "pyrit.prompt_converter", "UnicodeConfusableConverter", removed_in="0.5.0", source="manual"),

    # --- v0.2.0: Scorer rename ---
    ImportRename("pyrit.score", "SelfAskGptClassifier", "pyrit.score", "SelfAskScore", removed_in="0.2.0", source="manual"),

    # --- v0.1.2: RedTeamingBot removal ---
    ImportRename("pyrit.orchestrator", "RedTeamingBot", "pyrit.orchestrator", "RedTeamingOrchestrator", removed_in="0.1.2", source="manual"),
]

# ▲▲▲ END GENERATED IMPORT RENAMES ▲▲▲

# ▼▼▼ BEGIN GENERATED MODULE RENAMES ▼▼▼

MODULE_RENAMES: list[ModuleRename] = [
    ModuleRename("pyrit.orchestrator", "pyrit.executor.attack", removed_in="0.13.0", source="manual"),
    ModuleRename("pyrit.models.storage_io", "pyrit.memory.storage.storage", removed_in="0.17.0", source="shim"),
    ModuleRename("pyrit.models.data_type_serializer", "pyrit.memory.storage.serializers", removed_in="0.17.0", source="shim"),
]

# ▲▲▲ END GENERATED MODULE RENAMES ▲▲▲


# ---------------------------------------------------------------------------
# Auto-derived class renames (built from IMPORT_RENAMES where name changed)
# ---------------------------------------------------------------------------

CLASS_RENAMES: list[ClassRename] = [
    ClassRename(r.old_name, r.new_name)
    for r in IMPORT_RENAMES
    if r.old_name != r.new_name
]


# ---------------------------------------------------------------------------
# Manual rules (kwarg and method renames — not detectable from shims)
# ---------------------------------------------------------------------------

KWARG_RENAMES: list[KwargRename] = [
    # Standardized attack params (v0.5.0 orchestrator rename, carried into v0.10.0+ attack classes)
    KwargRename(r"(?:Attack|Orchestrator)", "prompt_target", "objective_target", "auto"),
    KwargRename(r"(?:Attack|Orchestrator)", "red_teaming_chat", "adversarial_chat", "auto"),
    KwargRename(r"(?:Attack|Orchestrator)", "attack_chat", "adversarial_chat", "auto"),
    KwargRename(r"(?:Attack|Orchestrator)", "max_rounds", "max_turns", "auto"),
    KwargRename(r"(?:Attack|Orchestrator)", "max_conversation_depth", "max_turns", "auto"),
    KwargRename(r"(?:Attack|Orchestrator)", "attack_strategy", "objective", "auto"),
    KwargRename(r"(?:Attack|Orchestrator)", "initial_red_teaming_prompt", "adversarial_chat_seed_prompt", "auto"),
    # Ambiguous — could appear in non-PyRIT code
    KwargRename(r"(?:Attack|Orchestrator)", "scorer", "objective_scorer", "suggestion"),
    # AttackResult field rename
    KwargRename(r"AttackResult", "attack_identifier", "atomic_attack_identifier", "auto"),
    # Memory interface
    KwargRename(r"get_attack_results", "attack_class", "attack_classes", "auto"),
    # v0.10.0: Scorer kwarg rename
    KwargRename(r"(?:Scorer|score_async)", "task", "objective", "suggestion"),
    # v0.10.0: OpenAI target kwarg changes
    KwargRename(r"OpenAI.*Target", "use_aad_auth", "api_key", "suggestion"),
    KwargRename(r"OpenAI.*Target", "use_entra_auth", "api_key", "suggestion"),
    # v0.5.0: OpenAI target unification
    KwargRename(r"OpenAIChatTarget", "is_azure_target", "is_azure_target", "auto"),
    # v0.8.0: AsciiSmugglerConverter
    KwargRename(r"AsciiSmugglerConverter", "unicode_tags", "encoding_mode", "auto"),
]

METHOD_RENAMES: list[MethodRename] = [
    MethodRename(r"(?:AttackResult|MessagePiece|Score)", r"\.to_dict\(\)", ".model_dump(mode='json')", "suggestion"),
    MethodRename(r"(?:AttackResult|MessagePiece|Score)", r"\.from_dict\(", ".model_validate(", "suggestion"),
    MethodRename(None, r"\.print_conversation_async\(", ".write_async(", "auto"),
    MethodRename(None, r"\.normalize_strategies\(", ".expand(", "auto"),
    MethodRename(None, r"\.from_json\(", ".from_json_file(", "suggestion"),
    # v0.3.0: Async migration
    MethodRename(None, r"\.send_prompt\(", ".send_prompt_async(", "suggestion"),
    MethodRename(None, r"\.convert\(", ".convert_async(", "suggestion"),
    # v0.10.0: Initialization
    MethodRename(None, r"\binitialize_pyrit\(\)", "await initialize_pyrit_async()", "auto"),
    # v0.12.1: Dataset function deprecation
    MethodRename(None, r"\bfetch_many_shot_jailbreaking_dataset\(", "load_many_shot_jailbreaking_dataset(", "auto"),
]
